server:
  port: 8081

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
#    username: gcpdb
#    password: 1q2w3e4r!!

    url: jdbc:h2:mem:test
    username: sa
    password:


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true